model:
  base-model-path: /home/nfs05/laizj/model/models--Qwen--Qwen2.5-Math-7B-Instruct/snapshots/ef9926d75ab1d54532f6a30dd5e760355eb9aa4d
inference:
  # beam-search: 
  #   beam-size: 5
  #   max-tokens: 2048
  sampling-params:
    temperature: 0.95
    top_p: 0.95
    max_tokens: 2048
    n: 5
data:
  # task: generate_template_and_code
  # source_dataset: orca_10k_train
  # model_name: qwen7b_instruct

  test-set-path: data/synthetic_data/qwen7b_instruct-generate_template_and_code-orca_20k_train-disturbed_1.0.json
  output-path: results/qwen7b_instruct-inference-greedy-qwen7b_instruct-generate-greedy-template_and_code-orca_20k_train_disturbed_1.0.json
