model:
  base-model-path: /home/nfs05/laizj/model/models--Qwen--Qwen2.5-Math-7B/snapshots/b101308fe89651ea5ce025f25317fea6fc07e96e
inference:
  sampling-params:
    temperature: 0.7
    top_p: 0.75
    max_tokens: 2048
    n: 5
data:
  test-set-path: data/gsm8k-train-prompt.json
  output-path: results/gsm8k-train-prompt_inference_0.7_0.75_5.json